/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetofinal.view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetofinal.dao.ProdutoDAO;
import projetofinal.model.Produto;
import projetofinal.jbcd.ConnectionFactory;
import java.sql.Connection;
import javax.swing.*;

/**
 *
 * @author eduardo
 */
public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPaneProdutos = new javax.swing.JTabbedPane();
        jPanelDadosPessoais = new javax.swing.JPanel();
        jLabelIdProduto = new javax.swing.JLabel();
        jTextFieldIdProduto = new javax.swing.JTextField();
        jLabelNomeProduto = new javax.swing.JLabel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jLabelQuantia = new javax.swing.JLabel();
        jTextFieldQuantia = new javax.swing.JTextField();
        jButtonNovoCadastroProduto = new javax.swing.JButton();
        jButtonEditarProduto = new javax.swing.JButton();
        jButtonExcluirProduto = new javax.swing.JButton();
        jTextFieldValorProduto = new javax.swing.JTextField();
        jPanelConsultaProdutos = new javax.swing.JPanel();
        jLabelNomeCon = new javax.swing.JLabel();
        jTextFieldPesquisaProduto = new javax.swing.JTextField();
        jButtonPesquisarProduto = new javax.swing.JButton();
        jScrollPaneCon = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanelCadastroProduto.setBackground(new java.awt.Color(0, 102, 204));
        jPanelCadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCadastroProdutoMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro Produtos");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroProdutoLayout = new javax.swing.GroupLayout(jPanelCadastroProduto);
        jPanelCadastroProduto.setLayout(jPanelCadastroProdutoLayout);
        jPanelCadastroProdutoLayout.setHorizontalGroup(
            jPanelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(609, Short.MAX_VALUE))
        );
        jPanelCadastroProdutoLayout.setVerticalGroup(
            jPanelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroProdutoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneProdutosMouseClicked(evt);
            }
        });

        jPanelDadosPessoais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDadosPessoaisMouseClicked(evt);
            }
        });

        jLabelIdProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIdProduto.setText("Identificador:");

        jTextFieldIdProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldIdProduto.setEnabled(false);
        jTextFieldIdProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIdProdutoMouseClicked(evt);
            }
        });
        jTextFieldIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdProdutoActionPerformed(evt);
            }
        });

        jLabelNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeProduto.setText("Nome:");

        jTextFieldNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeProdutoActionPerformed(evt);
            }
        });

        jTextFieldDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricao.setText("Descricao");

        jLabelPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPeso.setText("Peso");

        jTextFieldPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesoActionPerformed(evt);
            }
        });

        jLabelValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelValor.setText("Valor");

        jLabelQuantia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelQuantia.setText("Quantia");

        jTextFieldQuantia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldQuantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantiaActionPerformed(evt);
            }
        });

        jButtonNovoCadastroProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonNovoCadastroProduto.setText("NOVO CADASTRO");
        jButtonNovoCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCadastroProdutoActionPerformed(evt);
            }
        });

        jButtonEditarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEditarProduto.setText("ATUALIZAR");
        jButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProdutoActionPerformed(evt);
            }
        });

        jButtonExcluirProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExcluirProduto.setText("EXCLUIR");
        jButtonExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProdutoActionPerformed(evt);
            }
        });

        jTextFieldValorProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosPessoaisLayout = new javax.swing.GroupLayout(jPanelDadosPessoais);
        jPanelDadosPessoais.setLayout(jPanelDadosPessoaisLayout);
        jPanelDadosPessoaisLayout.setHorizontalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelIdProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescricao)
                            .addComponent(jLabelNomeProduto)
                            .addComponent(jLabelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jTextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabelQuantia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDescricao))
                                .addGap(51, 51, 51)
                                .addComponent(jLabelPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jButtonEditarProduto)
                                .addGap(53, 53, 53)
                                .addComponent(jButtonExcluirProduto))
                            .addComponent(jButtonNovoCadastroProduto))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanelDadosPessoaisLayout.setVerticalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdProduto)
                    .addComponent(jTextFieldIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomeProduto)
                            .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescricao)
                            .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValor)
                            .addComponent(jLabelQuantia)
                            .addComponent(jTextFieldQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPeso)
                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(93, 93, 93)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoCadastroProduto)
                    .addComponent(jButtonEditarProduto)
                    .addComponent(jButtonExcluirProduto))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPaneProdutos.addTab("Dados Produtos", jPanelDadosPessoais);

        jPanelConsultaProdutos.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNomeCon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeCon.setText("Nome:");

        jTextFieldPesquisaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaProdutoActionPerformed(evt);
            }
        });

        jButtonPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPesquisarProduto.setText("Pesquisar");
        jButtonPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarProdutoActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "nome ", "descricao", "peso", "valor", "quantidade"
            }
        ));
        jTableProdutos.setToolTipText("");
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPaneCon.setViewportView(jTableProdutos);

        javax.swing.GroupLayout jPanelConsultaProdutosLayout = new javax.swing.GroupLayout(jPanelConsultaProdutos);
        jPanelConsultaProdutos.setLayout(jPanelConsultaProdutosLayout);
        jPanelConsultaProdutosLayout.setHorizontalGroup(
            jPanelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCon)
                    .addGroup(jPanelConsultaProdutosLayout.createSequentialGroup()
                        .addComponent(jLabelNomeCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisarProduto)
                        .addGap(0, 275, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelConsultaProdutosLayout.setVerticalGroup(
            jPanelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisarProduto)
                    .addGroup(jPanelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNomeCon)
                        .addComponent(jTextFieldPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCon, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPaneProdutos.addTab("Consulta produtos", jPanelConsultaProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPaneProdutos)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(458, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jTabbedPaneProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdProdutoActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jTextFieldQuantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantiaActionPerformed

    private void jButtonNovoCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCadastroProdutoActionPerformed
        try {
            Produto produtos = new Produto();
            produtos.setNome(jTextFieldNomeProduto.getText());
            produtos.setDescicao(jTextFieldDescricao.getText());
            produtos.setPeso(Double.parseDouble(jTextFieldPeso.getText()));
            produtos.setValor(Double.parseDouble(jTextFieldValorProduto.getText()));
            produtos.setQtd_estoque(Integer.parseInt(jTextFieldQuantia.getText()));

            ProdutoDAO dao = new ProdutoDAO();
            dao.cadastrarProduto(produtos);
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonNovoCadastroProdutoActionPerformed

    private void jButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProdutoActionPerformed
       Produto produtos = new Produto();
            produtos.setNome(jTextFieldNomeProduto.getText());
            produtos.setDescicao(jTextFieldDescricao.getText());
            produtos.setPeso(Double.parseDouble(jTextFieldPeso.getText()));
            produtos.setValor(Double.parseDouble(jTextFieldValorProduto.getText()));
            produtos.setQtd_estoque(Integer.parseInt(jTextFieldQuantia.getText()));
            produtos.setId(Integer.parseInt(jTextFieldIdProduto.getText()));

            ProdutoDAO dao = new ProdutoDAO();
            dao.atualizarProduto(produtos);
    }//GEN-LAST:event_jButtonEditarProdutoActionPerformed

    private void jButtonExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProdutoActionPerformed
       
         Produto produtos = new Produto();
        produtos.setId(Integer.parseInt(jTextFieldIdProduto.getText()));

        ProdutoDAO dao = new ProdutoDAO();
        dao.deletarProduto(produtos);
    }//GEN-LAST:event_jButtonExcluirProdutoActionPerformed

    private void jTextFieldPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaProdutoActionPerformed

    private void jButtonPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarProdutoActionPerformed
       //Se o campo pesquisar estiver em branco, lista todos os clientes
        if (jTextFieldPesquisaProduto.getText().isBlank()) {
            //1º passo: criar um objeto DAO para podermos utilizar seus métodos
            ProdutoDAO dao = new ProdutoDAO();

            //2º passo: criar uma lista de endereços através do método listar
            //enderecos do DAO
            List<Produto> lista = dao.listarProduto();

            //3º passo: criar uma tabela do modelo padrão. Para isso pegamos o modelo
            //do componente jTable da tela através do método getModel() e convertemos
            //ele através de um casting para o modelo de tabela padrão.
            DefaultTableModel tabela = (DefaultTableModel) jTableProdutos.getModel();

            //4º passo: setamos o número de colunas de nossa tabela em zero para limpar
            // e garantir que não existem nenhum dado pré existente.
            tabela.setNumRows(0);

            //5º passo: precisamos colocar os itens da lista na tabela. Para cada objeto
            //do tipo Endereco na lista, nós adicionamos um novo objeto com os atributos
            //do objeto endereco nos seus campos separados por vírgula.
            for (Produto produtos : lista) { //este é um exemplo de uso do for-each
                tabela.addRow(new Object[]{ //este Object é um vetor/array
                    produtos.getId(),
                    produtos.getNome(),
                    produtos.getDescicao(),
                    produtos.getPeso(),
                    produtos.getValor(),
                    produtos.getQtd_estoque(),});
        }
        } else {
            //1º passo: criar um objeto DAO para podermos utilizar seus métodos
            ProdutoDAO dao = new ProdutoDAO();

            //2º passo: criar uma lista de endereços através do método listar
            //enderecos do DAO
            List<Produto> lista = dao.buscarProduto(jTextFieldPesquisaProduto.getText());

            //3º passo: criar uma tabela do modelo padrão. Para isso pegamos o modelo
            //do componente jTable da tela através do método getModel() e convertemos
            //ele através de um casting para o modelo de tabela padrão.
            DefaultTableModel tabela = (DefaultTableModel) jTableProdutos.getModel();

            //4º passo: setamos o número de colunas de nossa tabela em zero para limpar
            // e garantir que não existem nenhum dado pré existente.
            tabela.setNumRows(0);

            //5º passo: precisamos colocar os itens da lista na tabela. Para cada objeto
            //do tipo Endereco na lista, nós adicionamos um novo objeto com os atributos
            //do objeto endereco nos seus campos separados por vírgula.
            for (Produto produtos : lista) { //este é um exemplo de uso do for-each
                tabela.addRow(new Object[]{ //este Object é um vetor/array
                    produtos.getId(),
                    produtos.getNome(),
                    produtos.getDescicao(),
                    produtos.getPeso(),
                    produtos.getValor(),
                    produtos.getQtd_estoque(),});
        }
        }
    }//GEN-LAST:event_jButtonPesquisarProdutoActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
       jTextFieldIdProduto.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 0).toString());
       jTextFieldNomeProduto.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 1).toString());
       jTextFieldDescricao.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 2).toString());
       jTextFieldPeso.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 3).toString());
       jTextFieldValorProduto.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 4).toString());
       jTextFieldQuantia.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 5).toString());
      
       jTabbedPaneProdutos.setSelectedIndex(0);
       
       
      
      try {
            Connection conexao = ConnectionFactory.getConnection();
            //1º passo: criar uma lista para armazenar os clientes
            List<String> lista = new ArrayList<>();
            
            //2º passo: criar o comando sql que seleciona todos os itens da
            //tabela de endereços
            String sql = "select id from tb_produtos where id=?";
            
            //3º passo: preparar o comando colocando na conexao que será
            //utilizada para executá-lo no BD
            PreparedStatement comando = conexao.prepareStatement(sql);
            comando.setString(1, jTextFieldIdProduto.getText());
            
            //4º passo: quando usamos JDBC, o resultado de um comando select 
            //precisa ser armazenado em um objeto do tipo ResultSet
            ResultSet rs = comando.executeQuery();
            
            //5º passo: criar um laço de repetição para adicionar os itens do
            //ResultSet na lista criada no primeiro passo.
            while(rs.next()){ //Enquanto(while) conseguir percorrer o próximo (next) item do ResultSet
                lista.add(rs.getString("id"));       
            }
            //6º passo: após a lista ser criada, agora eu retorno como resultado
            // do meu método a lista pronta.
            
            
             
             
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            
            

        }
       
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void jTextFieldNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeProdutoActionPerformed

    private void jTextFieldValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorProdutoActionPerformed

    private void jPanelCadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastroProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelCadastroProdutoMouseClicked

    private void jTextFieldIdProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIdProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdProdutoMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jPanelDadosPessoaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDadosPessoaisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelDadosPessoaisMouseClicked

    private void jTabbedPaneProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneProdutosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneProdutosMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarProduto;
    private javax.swing.JButton jButtonExcluirProduto;
    private javax.swing.JButton jButtonNovoCadastroProduto;
    private javax.swing.JButton jButtonPesquisarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelIdProduto;
    private javax.swing.JLabel jLabelNomeCon;
    private javax.swing.JLabel jLabelNomeProduto;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelQuantia;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelCadastroProduto;
    private javax.swing.JPanel jPanelConsultaProdutos;
    private javax.swing.JPanel jPanelDadosPessoais;
    private javax.swing.JScrollPane jScrollPaneCon;
    private javax.swing.JTabbedPane jTabbedPaneProdutos;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldIdProduto;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldPesquisaProduto;
    private javax.swing.JTextField jTextFieldQuantia;
    private javax.swing.JTextField jTextFieldValorProduto;
    // End of variables declaration//GEN-END:variables
}
